
name: 'Typecheck'

on:
  workflow_run:
    workflows: ["Build And Test"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  Typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download build artifacts'
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-artifact
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success

      - name: 'Analyze Src log'
        if: always()
        id: logscan_src
        run: '.github/logscan.sh reports/typecheck.log'

      - name: 'TypeCheck Src'
        if: always()
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          name: 'Typecheck Src'
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{steps.logscan_src.conclusion}}
          output: |
            {"summary":"${{ steps.logscan_src.outputs.summary }}"}

      - name: 'Analyze Examples log'
        if: always()
        id: logscan_examples
        run: '.github/logscan.sh reports/typecheck-examples.log'

      - name: 'TypeCheck Examples'
        if: always()
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          name: 'Typecheck Examples'
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{steps.logscan_examples.conclusion}}
          output: |
            {"summary":"${{ steps.logscan_examples.outputs.summary }}"}
